### ISSUE TITLE
stack-picker 报错

### ISSUE THREAD

**Issue by sanheng** [ZhongAnTech/zarm-vue#70]
当选了值之后再次点击打开 StackPicker 的时候会报错

![1590548475(1)](https://user-images.githubusercontent.com/13793256/82973226-74073280-a009-11ea-94da-84088389f599.jpg)

**Comment by chuanshuoye** [comment]
哪个版本？

**Comment by sanheng** [comment]
> 哪个版本？

https://zarm-vue.gitee.io/#/documents/stack-picker 这里面的

**Comment by chuanshuoye** [comment]
beta.3 已修复
