### ISSUE TITLE
a problem in win10

### ISSUE THREAD

**Issue by zhangyin2019** [ZhongAnTech/zarm-vue#76]
The handler of the component load of Pull is not able to work in win10, i just use Google brower to task my project for loading data. But it can work in win7、android  brower、Safari.

**Comment by zhangyin2019** [comment]
by theway, I use zarm-react

**Comment by chuanshuoye** [comment]
zarm-react issue to link：https://github.com/ZhongAnTech/zarm/issues @zhangyin2019
