### ISSUE TITLE
carousel组件移动端做轮播图显示问题

### ISSUE THREAD

**Issue by huaerlan** [ZhongAnTech/zarm-vue#77]
用carousel组件在移动端做轮播图，rem单位布局，当前显示区域会出现部分下一张图片的内容，想了各种办法还是没有解决，不知道是不是因为用了rem单位导致translate的计算精度问题呢？

**Comment by chuanshuoye** [comment]
是纵向 还是横向

**Comment by huaerlan** [comment]
横向的

**Comment by chuanshuoye** [comment]
横向一般不需要设置具体宽度值吧，默认width:100%
